recyclingProject/recycleapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from . import views
from django.conf import settings

app_name='recycleapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('board/', views.board, name="board"),
    path('detail/<int:id>/', views.detail, name='detail'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recyclingProject/recyclingProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("recycleapp.urls")),
    path('log/', include("account.urls")),
    path('community/', include('ss_ba.urls')),
]

recyclingProject/ss_ba/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('new/', views.new, name='new'), # 상품 등록
    path('create/', views.create, name='create'), # 상품 등록
    path('', views.main, name='main'), # 등록된 게시글
    path('delete/<int:id>/', views.delete, name='delete'), # 임시
    path('detail/<int:id>/', views.detail, name='detail'), # 상품 상세
    path('edit/<int:id>/', views.edit, name='edit'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recyclingProject/recycleapp/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    TAG_CHOICES = (
        ('페트병 플라스틱류', '페트병 플라스틱류'),
        ('기타 플라스틱류', '기타 플라스틱류'),
        ('일반', '일반쓰레기'),
        ('음식물', '음식물쓰레기'),
        ('유리', '유리'),
        ('병', '병'),
        ('대형', '대형폐기물'),
        ('종이류', '종이류'),
        ('종이팩류', '종이팩류'),
        ('종이팩', '종이팩'),
        ('금속캔', '금속캔'),
        ('유리병류', '유리병류'),
        ('고철류', '고철류'),
        ('비닐류', '비닐류'),
        ('스티로폼 완충재', '스틔로폼 완충제'),
        ('의류','의류'),
        ('폐형광등','폐형광등'),
        ('폐건전지', '폐건전지'),
        ('폐가전제품','폐가전제품'),
        ('대형폐기물', '대형폐기물'),
        ('소형가전제품','소형가전제품'),
        
    )

    waste_name=models.CharField(max_length=50, verbose_name='카테고리')
    image = models.FileField(upload_to='images/')
    description = models.CharField(max_length = 500, verbose_name='처리방법')
    tag = models.CharField(max_length=20, choices=TAG_CHOICES)

    def __str__(self):
        return self.waste_name

recyclingProject/recycleapp/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate
from .models import Category


def home(request):
    waste = Category.objects.all()
    search = request.GET.get('search', '')
    
    a = request.user.is_authenticated
    b = request.user.username
    
    if search:
        waste = waste.filter(waste_name__icontains=search)
        return render(request, 'recycleapp/board.html', {'Cate': waste})
    else :
        return render(request, 'recycleapp/home.html', {'a':a, 'b':b})

def board(request):
    content = {}
    waste = Category.objects.all()
    try:
        search = request.GET.get('search', '')
        if search:
            waste = waste.filter(waste_name__icontains=search)
            print(waste)
            return render(request, 'recycleapp/board.html', {'Cate': waste})
        else:
            content={'Cate':waste,"a" : request.user.is_authenticated, "b" : request.user.username}
    except:
        print('=2' *30)

        errMsg = "서버 오류입니다."
        content={'errMsg':errMsg,}

    return render(request, 'recycleapp/board.html', content)


def detail(request, id):
    post = get_object_or_404(Category, pk=id)
    return render(request, 'recycleapp/detail.html',{'post': post})


    

recyclingProject/recycleapp/templates/recycleapp/board.html
{%extends "base/base.html" %}

{% block block1 %}
<h1 style="margin:20px auto; text-align: center;">분리수거 가능 품목</h1>
<hr>
<h2>{{errMsg}}</h2>
{%for board in boards%}
<a href="{% url 'recycleapp:detail' board.id %}">{{board.waste_name}}</a><br>
{% endfor %}
{% endblock %}
{% block block2 %}
<div class="container" sytle="height:1000px;">
    {% for po in Cate %}
    
    <div class="card item" style="width: 18rem; ">
        <img src= "{{po.image.url}}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{po.waste_name}}</h5>
          <p class="card-text">{{po.tag}} -자세히 보려면 ?</p>
          <a href="{% url 'recycleapp:detail' po.id %}" class="btn btn-primary">{{po.waste_name}}</a>
          
        </div>
      </div>   
      <br>
    {% endfor %}
  </div>

{% endblock %}
{% block block3 %}
{% endblock %}

recyclingProject/recycleapp/templates/recycleapp/detail.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        
        <title>설명</title>
        <style>
                .container {
                  display:flex; flex-wrap:wrap; justify-content: space-between;
                }
                .item {
                  align-items:center; 
                }
              </style>
      </head>
      <body>
          {% if post %}  
          <div class="container" style="margin-top:50px;">
                <div class="row item">
                    <div class="col-6">
                        {% if post.image %}
                        <img style="width: 90%;" src="{{ post.image.url }}" alt="example">
                        {% else %}
                        {% endif %}
                    </div>
                    <div class="col-6">
                    <div class="container" sytle="margin:0; padding:0;">
                        <div class="row">
                            <h3 class="display-4">제목 : {{ post.waste_name }}</h3>
                        </div>
                        <div class="row">
                            <p class="lead">이렇게 해 보아요 : {{ post.description }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
    <div class="alert alert-danger" role="alert">
        {{ errMsg }}
    </div>
    {% endif %}
<div class="row">
    <a style="text-align: center; margin:50px auto;" href="{% url 'recycleapp:board' %}"><h3></h3>뒤로</h3></a>
</div>

        

        

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      </body>
    </html>

recyclingProject/recycleapp/templates/recycleapp/home.html
  <!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>재활용의 정석</title>
  </head>
  <body>
    <div class="contain" style="height: 500px">
      <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-4"><img style="margin:200px auto 50px auto; height: 170px; width:420px;" src="media/배경.PNG"></div>
          <div class="col-md-2"></div>
          <div class="col-md-1" style="text-align: right; padding:0;">
              {% if a %}
              <a href="{% url 'logout' %}"> Logout</a>
              <br>
            {% else %}
              <a href="{% url 'login' %}"> Login</a>
              <br>
            {% endif %}
          </div>
          <div class="col-md-1">{{b}}</div>
      </div>
      <div class="row">
          <div class="col-md-4 col-sm-12"></div>
          <div class="col-md-4 col-sm-12">
              <form action="{% url 'recycleapp:home' %}" method="GET">
                  <div class="input-group input-group-lg" style="width: 420px;">
                      <input type="text" class="form-control" aria-label="Sizing example input"
                             aria-describedby="inputGroup-sizing-lg" name="search">
                      <div class="input-group-prepend">
                          <button class="btn btn-outline-secondary" type="submit" id="button-addon1">엇따버려?</button>
                      </div>
                  </div>
              </form>
          </div>
          <div class="col-md-4 col-sm-12"></div>
      </div>
      <div class="row" style="margin-top:20px;">
          <div class="col-md-4 col-sm-12"></div>
          <div class="col-md-4 col-sm-12">
            <div class="row">
              <div class="col-4"style="text-align: right; padding:0;">
                  <a href="{% url 'recycleapp:board' %}"> Board</a>
              </div>
              <div class="col-4"></div>
              <div class="col-4">
                  <a href="{% url 'main' %}">SS_ba</a>
              </div>
            </div> 
          </div>
          <div class="col-md-4 col-sm-12"></div>
      </div>
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>